### ISSUE TITLE
Irc channel 

### ISSUE THREAD

**Issue by posix4e** [stainless-steel/tensorflux#9]
Can we all merge on #rust-tensorflow on rust irc? I'm going to try to get rust-tensorflow there as well

**Comment by IvanUkhov** [comment]
Sorry, what do you mean by that?

**Comment by posix4e** [comment]
I am curious if you are ok with:
- Using IRC to chat with users
- Having that irc room being rust-tensorflow
- That happens to be the same channel that I suggested for rust-tensorflow. I figure no reason y'all can't combine channels.

**Comment by IvanUkhov** [comment]
I think it’s a good idea to have a common place to talk about TensorFlow in Rust. However, why can’t we use the channels that already exist? I’m specifically referring to #rust-machine-learning on Mozilla’s server, which is perfectly suited for this kind of discussions.

**Comment by posix4e** [comment]
I fully support rust-machine-learning. I'll update the PR to reflect this

**Comment by IvanUkhov** [comment]
I close this as discussed in #11.
